kind: pipeline
name: default

steps:
- name: docker  
  image: plugins/docker
  settings:
    context: app
    dockerfile: app/Dockerfile
    tags: 
      - latest
      - ${DRONE_TAG}
    repo: jjtc/bookstack-ppm
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    branch:
      - master
    event:
      - tag